### ISSUE TITLE
python show.py --src ../data/data  --from h5

### ISSUE THREAD

**Issue by hanyong-max** [ChrisWu1997/DeepCAD#17]
Traceback (most recent call last):
  File "D:\DeepCAD-master\utils\show.py", line 6, in <module>
    from OCC.Display.SimpleGui import init_display
ModuleNotFoundError: No module named 'OCC'

**Comment by hanyong-max** [comment]
(base) D:\DeepCAD-master\dataset>python json2pc.py --only_test

Traceback (most recent call last):
  File "D:\DeepCAD-master\dataset\json2pc.py", line 13, in <module>
    from cadlib.visualize import CADsolid2pc, create_CAD
  File "D:\DeepCAD-master\dataset\..\cadlib\visualize.py", line 1, in <module>
    from OCC.Core.gp import gp_Pnt, gp_Dir, gp_Circ, gp_Pln, gp_Vec, gp_Ax3, gp_Ax2, gp_Lin
ModuleNotFoundError: No module named 'OCC'
