### ISSUE TITLE
h5格式无法可视化

### ISSUE THREAD

**Issue by hanyong-max** [ChrisWu1997/DeepCAD#18]
(DeepCAD) D:\DeepCAD-master\utils>python export2step.py --src ../data/cad_vec/0000 --form h5
../data/cad_vec/0000\00000007.h5
Traceback (most recent call last):
  File "export2step.py", line 38, in <module>
    out_vec = fp["out_vec"][:].astype(np.float)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "D:\Anaconda3\envs\DeepCAD\lib\site-packages\h5py\_hl\group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'out_vec' doesn't exist)"

**Comment by chachachachachaxxxxx** [comment]
```python
out_vec = fp["vec"][:].astype(np.float)
out_shape = vec2CADsolid(out_vec)
# if args.with_gt:
#     gt_vec = fp["gt_vec"][:].astype(np.float)
#     gt_shape = vec2CADsolid(gt_vec)
```
change out_vec to vec
